export interface Campaign {
  id: string;
  name: string;
  brand: string;
  year: number;
  industry: string;
  targetAudience: string[];
  objectives: string[];
  keyMessage: string;
  strategy: string;
  features: string[];
  emotionalAppeal: string[];
  outcomes: string[];
}

export const campaignData: Campaign[] = [
  {
    id: "1",
    name: "Like a Girl",
    brand: "Always",
    year: 2014,
    industry: "Personal Care",
    targetAudience: ["Women", "Teenage Girls", "Young Adults"],
    objectives: ["Brand Awareness", "Societal Change", "Emotional Connection"],
    keyMessage: "Redefine what it means to do something 'like a girl'",
    strategy: "Challenge negative stereotypes about female capability through powerful social experiment video",
    features: ["Social Media Campaign", "Emotional Video Content", "Documentary Style"],
    emotionalAppeal: ["Empowerment", "Pride", "Social Justice"],
    outcomes: ["Increased Brand Awareness", "Cultural Impact", "Sales Growth"]
  },
  {
    id: "2",
    name: "Share a Coke",
    brand: "Coca-Cola",
    year: 2011,
    industry: "Beverages",
    targetAudience: ["Millennials", "General Public", "Families"],
    objectives: ["Increase Consumption", "Brand Connection", "Social Media Engagement"],
    keyMessage: "Share happiness with someone special in your life",
    strategy: "Replace Coca-Cola logo with popular names on bottles to create personal connections",
    features: ["Personalized Packaging", "User-Generated Content", "Social Sharing"],
    emotionalAppeal: ["Nostalgia", "Friendship", "Happiness"],
    outcomes: ["Sales Increase", "Social Media Engagement", "Brand Affinity"]
  },
  {
    id: "3",
    name: "Fearless Girl",
    brand: "State Street Global Advisors",
    year: 2017,
    industry: "Finance",
    targetAudience: ["Investors", "Business Leaders", "Working Women"],
    objectives: ["Brand Awareness", "Social Statement", "Investment Product Promotion"],
    keyMessage: "Advocate for gender diversity in corporate leadership",
    strategy: "Place statue of a young girl facing Wall Street's Charging Bull to symbolize female empowerment",
    features: ["Public Art Installation", "Symbolic Imagery", "Media Relations"],
    emotionalAppeal: ["Courage", "Defiance", "Empowerment"],
    outcomes: ["28 Billion Media Impressions", "Industry Recognition", "Cultural Impact"]
  },
  {
    id: "4",
    name: "Real Beauty Sketches",
    brand: "Dove",
    year: 2013,
    industry: "Personal Care",
    targetAudience: ["Women", "Young Adults"],
    objectives: ["Brand Values Communication", "Emotional Connection", "Social Media Sharing"],
    keyMessage: "You are more beautiful than you think",
    strategy: "Create a social experiment where women describe themselves to a forensic artist who draws them unseen",
    features: ["Documentary Style Video", "Emotional Storytelling", "Social Experiment"],
    emotionalAppeal: ["Self-Acceptance", "Empathy", "Reflection"],
    outcomes: ["114 Million Views", "Media Coverage", "Brand Perception Improvement"]
  },
  {
    id: "5",
    name: "Dream Crazy",
    brand: "Nike",
    year: 2018,
    industry: "Sportswear",
    targetAudience: ["Athletes", "Social Justice Supporters", "Youth"],
    objectives: ["Brand Positioning", "Social Statement", "Emotional Connection"],
    keyMessage: "Believe in something, even if it means sacrificing everything",
    strategy: "Feature Colin Kaepernick and other athletes who overcame obstacles to achieve greatness",
    features: ["Celebrity Endorsement", "Inspirational Storytelling", "Social Commentary"],
    emotionalAppeal: ["Inspiration", "Determination", "Justice"],
    outcomes: ["Brand Value Increase", "Cultural Impact", "Sales Growth"]
  },
  {
    id: "6",
    name: "Spotify Wrapped",
    brand: "Spotify",
    year: 2016,
    industry: "Music Streaming",
    targetAudience: ["Music Lovers", "Digital Natives", "Social Media Users"],
    objectives: ["User Engagement", "Brand Loyalty", "Social Media Sharing"],
    keyMessage: "Celebrate your unique music taste and year in review",
    strategy: "Create personalized data stories for users showcasing their listening habits",
    features: ["Personalized Content", "Data Visualization", "Shareable Format"],
    emotionalAppeal: ["Nostalgia", "Identity", "Connection"],
    outcomes: ["Massive Social Sharing", "User Retention", "Brand Differentiation"]
  },
  {
    id: "7",
    name: "The Truth Is Worth It",
    brand: "The New York Times",
    year: 2019,
    industry: "Media",
    targetAudience: ["News Readers", "Educated Professionals", "Truth Seekers"],
    objectives: ["Subscription Growth", "Brand Positioning", "Editorial Value"],
    keyMessage: "The pursuit of truth requires resources and determination",
    strategy: "Showcase the challenging process journalists go through to uncover important stories",
    features: ["Documentary Style", "Intense Visuals", "Emotional Soundtrack"],
    emotionalAppeal: ["Truth", "Integrity", "Determination"],
    outcomes: ["Subscription Increase", "Award Recognition", "Brand Perception"]
  },
  {
    id: "8",
    name: "Thank You Mom",
    brand: "P&G",
    year: 2012,
    industry: "Consumer Goods",
    targetAudience: ["Mothers", "Families", "Olympic Viewers"],
    objectives: ["Brand Association", "Emotional Connection", "Olympic Sponsorship Leverage"],
    keyMessage: "Behind every Olympic athlete is a supportive mother",
    strategy: "Connect P&G products to mothers' support of their children's Olympic dreams",
    features: ["Olympic Tie-in", "Emotional Storytelling", "Multi-brand Approach"],
    emotionalAppeal: ["Gratitude", "Family", "Pride"],
    outcomes: ["$500M in Sales", "Brand Association", "Positive Sentiment"]
  },
  {
    id: "9",
    name: "The Man Your Man Could Smell Like",
    brand: "Old Spice",
    year: 2010,
    industry: "Personal Care",
    targetAudience: ["Women", "Young Men"],
    objectives: ["Brand Rejuvenation", "New Customer Acquisition", "Social Media Engagement"],
    keyMessage: "Anything is possible with Old Spice",
    strategy: "Use absurd humor and a charismatic spokesperson to appeal to women who purchase for men",
    features: ["Humor", "Unique Character", "One-Take Video"],
    emotionalAppeal: ["Humor", "Attraction", "Confidence"],
    outcomes: ["107% Sales Increase", "Cultural Phenomenon", "Brand Repositioning"]
  },
  {
    id: "10",
    name: "Dumb Ways to Die",
    brand: "Metro Trains Melbourne",
    year: 2012,
    industry: "Public Safety",
    targetAudience: ["Young Adults", "Teenagers", "Commuters"],
    objectives: ["Safety Awareness", "Behavior Change", "Engagement with Serious Message"],
    keyMessage: "Be safe around trains - a serious message delivered in an engaging way",
    strategy: "Use cute characters and catchy music to communicate train safety in a memorable way",
    features: ["Animated Characters", "Catchy Song", "Mobile Game"],
    emotionalAppeal: ["Humor", "Surprise", "Memorability"],
    outcomes: ["200 Million Views", "21% Reduction in Accidents", "Global Recognition"]
  },
  {
    id: "11",
    name: "The Everyday Tactician",
    brand: "Xbox",
    year: 2023,
    industry: "Gaming",
    targetAudience: ["Football fans", "Gamers"],
    objectives: ["Brand Awareness", "Product Promotion", "Consumer Engagement"],
    keyMessage: "Football Manager players are incredibly dedicated and their skills can translate to the real world",
    strategy: "Turned Football Manager 2024 into a recruitment platform for Bromley FC by having gamers complete an achievement in the game and go through an interview process",
    features: ["Partnership with Football Manager", "Docuseries", "Real-world Job Opportunity"],
    emotionalAppeal: ["Passion", "Dedication", "Achievement"],
    outcomes: ["New Tactician Hire", "Increased Game Pass Users", "Media Coverage"]
  },
  {
    id: "12",
    name: "Napapitas (The Lucky Fry)",
    brand: "McDonald's",
    year: 2023,
    industry: "Fast Food",
    targetAudience: ["Puerto Rico Residents", "Fast Food Consumers"],
    objectives: ["Product Launch", "Customer Engagement", "Sales Growth"],
    keyMessage: "McDonald's is listening to its customers and is willing to make their dreams come true, even if they started as a joke",
    strategy: "Redesigned the iconic packaging of McDonald's fries to resemble a potato wedge and launched the product on International French Fry Day",
    features: ["Packaging Redesign", "Social Media Campaign", "Limited Edition Product"],
    emotionalAppeal: ["Humor", "Excitement", "Novelty"],
    outcomes: ["25% Sales Increase", "50 Million Media Impressions", "Sold Out in 6 Hours"]
  },
  {
    id: "13",
    name: "DoorDash-All-The-Ads",
    brand: "DoorDash",
    year: 2024,
    industry: "Food Delivery",
    targetAudience: ["Super Bowl Viewers", "Convenience Seekers"],
    objectives: ["Brand Differentiation", "Service Expansion Awareness", "Consumer Engagement"],
    keyMessage: "DoorDash can deliver anything you see advertised, even during the Super Bowl",
    strategy: "Partnered with every brand that advertised during the Super Bowl and offered to deliver their products to viewers in real-time",
    features: ["Real-time Engagement", "Cross-brand Partnerships", "Super Bowl Tie-in"],
    emotionalAppeal: ["Excitement", "Convenience", "Participation"],
    outcomes: ["11.9 Billion Impressions", "8 Million Submissions", "75+ Brand Partnerships"]
  },
  {
    id: "14",
    name: "Pub Museums",
    brand: "Heineken",
    year: 2023,
    industry: "Alcohol",
    targetAudience: ["Cultural Enthusiasts", "Tourists", "History Buffs"],
    objectives: ["Cultural Preservation", "Brand Positioning", "Community Support"],
    keyMessage: "Heineken is committed to preserving Irish culture and heritage",
    strategy: "Partnered with the Irish government to grant tax exemptions and financial support to pubs that turn themselves into virtual museums",
    features: ["Augmented Reality Technology", "Government Partnership", "Cultural Preservation"],
    emotionalAppeal: ["Nostalgia", "Cultural Pride", "Community Spirit"],
    outcomes: ["Positive Media Coverage", "Increased Awareness", "Heritage Preservation"]
  },
  {
    id: "15",
    name: "McCode",
    brand: "McDonald's",
    year: 2022,
    industry: "Fast Food",
    targetAudience: ["McDonald's Customers", "Discount Seekers"],
    objectives: ["Coupon Conversion", "Customer Engagement", "Digital Integration"],
    keyMessage: "McDonald's is making it easier and more fun to save money",
    strategy: "Created unique barcodes for each McDonald's sandwich that could be scanned using mobile phones for discounts",
    features: ["Mobile Integration", "Visual Barcodes", "Unique Product Codes"],
    emotionalAppeal: ["Convenience", "Excitement", "Novelty"],
    outcomes: ["36% Increase in Coupon Conversion", "Customer Engagement", "Digital Adoption"]
  },
  {
    id: "16",
    name: "The Blind Taste",
    brand: "McDonald's",
    year: 2023,
    industry: "Fast Food",
    targetAudience: ["Food Quality Skeptics", "Italian Consumers"],
    objectives: ["Perception Change", "Quality Demonstration", "Sales Growth"],
    keyMessage: "McDonald's food tastes better than you think",
    strategy: "Opened a restaurant without McDonald's branding that served classic McDonald's burgers without revealing their origin until after customers had tasted them",
    features: ["Blind Taste Test", "Unbranded Restaurant", "Reveal Experience"],
    emotionalAppeal: ["Surprise", "Curiosity", "Discovery"],
    outcomes: ["10.7% Sales Increase", "Media Coverage", "Perception Change"]
  },
  {
    id: "17",
    name: "Gatorade Turf Finder",
    brand: "Gatorade",
    year: 2023,
    industry: "Sports Drink",
    targetAudience: ["Sports Enthusiasts", "Mumbai Residents", "Active Individuals"],
    objectives: ["Community Support", "Brand Positioning", "Product Growth"],
    keyMessage: "Gatorade is committed to making sports more accessible",
    strategy: "Developed an app using Google Maps data to locate sports turfs across Mumbai. Partnered with local authorities for new turf allocation",
    features: ["Mobile App Development", "Real-time Availability Data", "Government Partnership"],
    emotionalAppeal: ["Community Spirit", "Sports Passion", "Accessibility"],
    outcomes: ["20+ New Turfs Allocated", "121% Product Volume Growth", "Community Engagement"]
  },
  {
    id: "18",
    name: "The Missing Chapter",
    brand: "P&G Whisper",
    year: 2022,
    industry: "Consumer Goods",
    targetAudience: ["Young Women", "Girls", "Indian Education System"],
    objectives: ["Health Education", "Social Impact", "Brand Positioning"],
    keyMessage: "Menstrual education is vital for young girls to understand their bodies",
    strategy: "Created an educational campaign that added a missing chapter on menstrual health to school curriculums across India",
    features: ["Curriculum Integration", "Educational Content", "Government Partnerships"],
    emotionalAppeal: ["Empowerment", "Education", "Support"],
    outcomes: ["Cannes Lions Grand Prix", "Curriculum Integration", "Educational Impact"]
  },
  {
    id: "19",
    name: "Piñatex",
    brand: "Dole Products",
    year: 2022,
    industry: "Food & Beverage/Agriculture",
    targetAudience: ["Eco-conscious Consumers", "Fashion Brands", "Sustainability Advocates"],
    objectives: ["Sustainable Innovation", "Waste Reduction", "Brand Positioning"],
    keyMessage: "Sustainability can be achieved using natural waste products",
    strategy: "Developed Piñatex—a leather alternative made from discarded pineapple leaves",
    features: ["Upcycled Materials", "Cross-industry Innovation", "Sustainable Product"],
    emotionalAppeal: ["Sustainability", "Innovation", "Environmental Consciousness"],
    outcomes: ["Creative Business Transformation Grand Prix", "Material Adoption", "Waste Reduction"]
  },
  {
    id: "20",
    name: "Runner321",
    brand: "Adidas",
    year: 2023,
    industry: "Sportswear/Apparel",
    targetAudience: ["Athletes with Disabilities", "Inclusive Sports Community", "General Public"],
    objectives: ["Inclusive Representation", "Brand Positioning", "Social Impact"],
    keyMessage: "Everyone deserves representation in sports marketing",
    strategy: "Featured Chris Nikic (the first person with Down syndrome to complete an Ironman) as part of Adidas' campaign promoting inclusivity in running events",
    features: ["Inclusive Athlete Representation", "Stereotype Breaking", "Authentic Storytelling"],
    emotionalAppeal: ["Inspiration", "Empowerment", "Inclusion"],
    outcomes: ["Positive Media Coverage", "Brand Affinity", "Community Support"]
  },
  {
    id: "21",
    name: "Self Love Bouquet",
    brand: "DoorDash",
    year: 2023,
    industry: "Food Delivery",
    targetAudience: ["Self-care Advocates", "Gift Givers", "Social Media Users"],
    objectives: ["Concept Promotion", "Brand Positioning", "Social Media Engagement"],
    keyMessage: "Gifting yourself flowers is a powerful act of self-love",
    strategy: "Created a limited-edition flower arrangement called the 'Self-Love Bouquet' available through DoorDash for customers who want to practice self-love",
    features: ["Limited Edition Product", "Self-care Messaging", "Delivery Service"],
    emotionalAppeal: ["Self-care", "Self-love", "Empowerment"],
    outcomes: ["Social Media Engagement", "Positive Press Coverage", "Brand Positioning"]
  },
  {
    id: "22",
    name: "Bar Experience",
    brand: "Heineken",
    year: 2023,
    industry: "Alcohol",
    targetAudience: ["Potential Bar Staff", "Hospitality Workers", "Career Seekers"],
    objectives: ["Industry Perception Change", "Professional Development", "Brand Positioning"],
    keyMessage: "Working behind a bar can be a rewarding and valuable experience that contributes to your career",
    strategy: "Repositioned bar work as valuable career experience to be included on resumes",
    features: ["Professional Development Focus", "Career Positioning", "Industry Support"],
    emotionalAppeal: ["Professional Pride", "Career Development", "Recognition"],
    outcomes: ["Industry Recognition", "Career Perception Change", "Brand Positioning"]
  },
  {
    id: "23",
    name: "MayoHaters",
    brand: "NotCo",
    year: 2023,
    industry: "Food & Beverage",
    targetAudience: ["Mayo Skeptics", "Plant-based Food Adopters", "Alternative Food Seekers"],
    objectives: ["Product Promotion", "Perception Challenge", "Market Expansion"],
    keyMessage: "NotCo's plant-based mayo tastes so good, even mayo haters love it",
    strategy: "Targeted consumers who dislike traditional mayonnaise to try the plant-based alternative",
    features: ["Focus Group Concept", "Taste Challenge", "Alternative Positioning"],
    emotionalAppeal: ["Surprise", "Curiosity", "Food Discovery"],
    outcomes: ["Perception Change", "Product Adoption", "Market Expansion"]
  },
  {
    id: "24",
    name: "We Are Ayenda",
    brand: "WhatsApp",
    year: 2023,
    industry: "Technology",
    targetAudience: ["Global Audience", "Privacy Advocates", "Digital Communication Users"],
    objectives: ["Privacy Awareness", "Product Utility", "Social Impact"],
    keyMessage: "WhatsApp can be a lifeline for people facing danger and needing to communicate securely",
    strategy: "Highlighted real-world cases where WhatsApp's secure communication was crucial in crisis situations",
    features: ["Documentary Storytelling", "Real Stories", "Crisis Communication"],
    emotionalAppeal: ["Security", "Hope", "Connection"],
    outcomes: ["550 Million Impressions", "Amazon Prime Documentary", "Positive PR"]
  },
  {
    id: "25",
    name: "The Unfiltered History Tour",
    brand: "Vice World News",
    year: 2022,
    industry: "Media",
    targetAudience: ["History Enthusiasts", "Cultural Critics", "Museum Visitors"],
    objectives: ["Alternative Narrative", "Cultural Perspective", "Media Innovation"],
    keyMessage: "Challenging traditional narratives by showcasing stolen artefacts and providing insights from the perspective of the colonised",
    strategy: "Created an augmented reality tour of the British Museum that presented colonial history from the perspective of colonized peoples",
    features: ["Augmented Reality", "Podcast Integration", "Museum Experience"],
    emotionalAppeal: ["Cultural Justice", "Historical Truth", "Educational Discovery"],
    outcomes: ["35,300 Podcast Downloads", "18 Million Social Impressions", "100,000+ Tours"]
  },
  {
    id: "26",
    name: "iPager",
    brand: "Android",
    year: 2023,
    industry: "Technology",
    targetAudience: ["Smartphone Users", "Tech Enthusiasts", "Apple Users"],
    objectives: ["Technology Comparison", "Competitor Challenge", "Standard Adoption"],
    keyMessage: "Highlighting the benefits of RCS and portraying Apple's SMS as outdated",
    strategy: "Created a campaign comparing Apple's SMS technology to outdated pagers to highlight the need for RCS adoption",
    features: ["Competitor Comparison", "Technology Education", "Humor"],
    emotionalAppeal: ["Technological Progress", "Frustration with Limitations", "Industry Standards"],
    outcomes: ["One Show Merit Award", "Online Buzz", "Industry Discussion"]
  },
  {
    id: "27",
    name: "WoMen's Football",
    brand: "Orange",
    year: 2023,
    industry: "Telecommunications",
    targetAudience: ["Football Fans", "Gender Equality Supporters", "Sports Community"],
    objectives: ["Gender Equality", "Sports Promotion", "Brand Association"],
    keyMessage: "Supporting and celebrating women's football",
    strategy: "Created a campaign highlighting women's football to promote gender equality in sports",
    features: ["Gender Equality Focus", "Sports Partnership", "Inclusive Messaging"],
    emotionalAppeal: ["Equality", "Sports Passion", "Recognition"],
    outcomes: ["Grand Clio Award", "Sports Community Support", "Brand Positioning"]
  },
  {
    id: "28",
    name: "Pop-Tarts Bowl: The Edible Mascot",
    brand: "Pop-Tarts (Kellanova)",
    year: 2023,
    industry: "Food & Beverage",
    targetAudience: ["College Football Fans", "Pop-Tarts Consumers", "Event Attendees"],
    objectives: ["Product Positioning", "Event Marketing", "Brand Buzz"],
    keyMessage: "Pop-Tarts brings 'Crazy Good' flavor to the college football experience",
    strategy: "Created an edible mascot for a college football bowl game to generate buzz and associate the brand with sports events",
    features: ["Edible Mascot", "Sports Sponsorship", "Social Media Integration"],
    emotionalAppeal: ["Humor", "Novelty", "Sports Excitement"],
    outcomes: ["4 Billion+ Impressions", "$1M First-party Data", "15x More Brand Mentions"]
  },
  {
    id: "29",
    name: "Spreadbeats",
    brand: "Spotify",
    year: 2023,
    industry: "Music Streaming",
    targetAudience: ["Advertisers", "Media Buyers", "Tech-savvy Individuals"],
    objectives: ["Platform Showcase", "Advertising Innovation", "Data Capability Demonstration"],
    keyMessage: "Spotify's ad platform allows for innovative and emotionally engaging experiences through data",
    strategy: "Created a music video coded and experienced entirely in a media plan to showcase Spotify's advertising capabilities",
    features: ["Innovative Format", "Data Integration", "Emotional Experience"],
    emotionalAppeal: ["Creativity", "Innovation", "Emotional Connection"],
    outcomes: ["Industry Recognition", "Platform Adoption", "Advertiser Interest"]
  },
  {
    id: "30",
    name: "WeAre8",
    brand: "WeAre8",
    year: 2023,
    industry: "Social Impact",
    targetAudience: ["Socially Conscious Consumers", "Food Security Advocates", "Community Members"],
    objectives: ["Social Mobilization", "Hunger Relief", "Community Engagement"],
    keyMessage: "Addressing the modern-day food crisis and encouraging community involvement",
    strategy: "Used an app to facilitate donations and collaboration with charity partners to provide meals to those in need",
    features: ["Mobile App", "Charity Partnerships", "Social Media Integration"],
    emotionalAppeal: ["Empathy", "Urgency", "Community Support"],
    outcomes: ["80,000 Meals in 8 Weeks", "Community Engagement", "Social Impact"]
  }
];

export const industries = [
  "Automotive", 
  "Beverages", 
  "Consumer Electronics", 
  "Consumer Goods", 
  "Entertainment", 
  "Fashion", 
  "Finance", 
  "Food", 
  "Food & Beverage",
  "Food & Beverage/Agriculture",
  "Food Delivery",
  "Gaming",
  "Healthcare", 
  "Hospitality", 
  "Media", 
  "Music Streaming", 
  "Personal Care", 
  "Public Safety", 
  "Retail", 
  "Social Impact",
  "Social Media", 
  "Sportswear", 
  "Sportswear/Apparel",
  "Sports Drink",
  "Technology", 
  "Telecommunications", 
  "Travel"
];

export const emotionalAppeals = [
  "Achievement",
  "Adventure", 
  "Ambition", 
  "Amusement", 
  "Attraction", 
  "Belonging", 
  "Career Development",
  "Comfort", 
  "Community Spirit",
  "Community Support",
  "Confidence", 
  "Connection", 
  "Convenience",
  "Courage", 
  "Creativity",
  "Cultural Justice",
  "Cultural Pride",
  "Curiosity",
  "Dedication",
  "Defiance", 
  "Determination", 
  "Discovery",
  "Educational Discovery",
  "Empathy", 
  "Empowerment", 
  "Environmental Consciousness",
  "Equality",
  "Excitement", 
  "Family", 
  "Food Discovery",
  "Friendship", 
  "Frustration with Limitations",
  "Gratitude", 
  "Happiness", 
  "Historical Truth",
  "Hope", 
  "Humor", 
  "Identity", 
  "Inclusion",
  "Industry Standards",
  "Innovation",
  "Inspiration", 
  "Integrity", 
  "Joy", 
  "Justice", 
  "Love", 
  "Memorability", 
  "Nostalgia", 
  "Novelty",
  "Optimism", 
  "Participation",
  "Passion", 
  "Pride", 
  "Professional Pride",
  "Recognition",
  "Reflection", 
  "Security",
  "Self-Acceptance", 
  "Self-care",
  "Self-love",
  "Social Excitement",
  "Social Justice",
  "Sports Excitement", 
  "Sports Passion",
  "Surprise", 
  "Sustainability",
  "Technological Progress",
  "Trust", 
  "Truth",
  "Urgency"
];

export const objectives = [
  "Alternative Narrative",
  "Behavior Change", 
  "Brand Association", 
  "Brand Awareness", 
  "Brand Buzz",
  "Brand Connection", 
  "Brand Differentiation", 
  "Brand Loyalty", 
  "Brand Perception Improvement", 
  "Brand Positioning", 
  "Brand Rejuvenation", 
  "Brand Values Communication",
  "Competitor Challenge",
  "Concept Promotion",
  "Consumer Engagement",
  "Coupon Conversion",
  "Cultural Impact",
  "Cultural Perspective",
  "Cultural Preservation", 
  "Customer Engagement",
  "Data Capability Demonstration",
  "Digital Integration",
  "Editorial Value", 
  "Emotional Connection", 
  "Engagement with Serious Message", 
  "Event Marketing",
  "Gender Equality",
  "Health Education",
  "Hunger Relief",
  "Inclusive Representation",
  "Increase Consumption", 
  "Industry Perception Change",
  "Investment Product Promotion", 
  "Market Expansion",
  "Media Coverage", 
  "Media Innovation",
  "New Customer Acquisition", 
  "Olympic Sponsorship Leverage", 
  "Perception Change",
  "Platform Showcase",
  "Privacy Awareness",
  "Product Growth",
  "Product Launch",
  "Product Positioning",
  "Product Promotion",
  "Product Utility",
  "Professional Development",
  "Quality Demonstration",
  "Safety Awareness", 
  "Sales Growth", 
  "Service Expansion Awareness",
  "Social Impact",
  "Social Media Engagement", 
  "Social Media Sharing", 
  "Social Mobilization",
  "Social Statement", 
  "Societal Change", 
  "Sports Promotion",
  "Standard Adoption",
  "Subscription Growth", 
  "Sustainable Innovation",
  "Technology Comparison",
  "User Engagement", 
  "User Retention",
  "Waste Reduction"
];

export const targetAudiences = [
  "Active Individuals",
  "Advertisers",
  "Alternative Food Seekers",
  "Apple Users",
  "Athletes", 
  "Athletes with Disabilities",
  "Business Leaders",
  "Career Seekers",
  "Charity Supporters",
  "College Football Fans",
  "Commuters", 
  "Community Members",
  "Convenience Seekers",
  "Cultural Critics",
  "Cultural Enthusiasts",
  "Digital Natives", 
  "Eco-conscious Consumers",
  "Educated Professionals",
  "Event Attendees",
  "Families", 
  "Fashion Brands",
  "Food Quality Skeptics",
  "Football fans",
  "Gamers",
  "Gender Equality Supporters",
  "General Public", 
  "Gift Givers",
  "Girls",
  "Global Audience",
  "History Buffs",
  "History Enthusiasts",
  "Hospitality Workers",
  "Inclusive Sports Community",
  "Indian Education System",
  "Investors", 
  "Italian Consumers",
  "Mayo Skeptics",
  "McDonald's Customers",
  "Media Buyers",
  "Millennials", 
  "Mothers", 
  "Mumbai Residents",
  "Museum Visitors",
  "Music Lovers", 
  "News Readers", 
  "Olympic Viewers", 
  "Plant-based Food Adopters",
  "Pop-Tarts Consumers",
  "Potential Bar Staff",
  "Privacy Advocates",
  "Puerto Rico Residents",
  "Self-care Advocates",
  "Smartphone Users",
  "Social Justice Supporters", 
  "Social Media Users", 
  "Socially Conscious Consumers",
  "Sports Community",
  "Sports Enthusiasts",
  "Super Bowl Viewers",
  "Sustainability Advocates",
  "Teenage Girls", 
  "Teenagers", 
  "Tech Enthusiasts",
  "Tourists",
  "Truth Seekers", 
  "Women", 
  "Working Women", 
  "Young Adults", 
  "Young Men", 
  "Young Women",
  "Youth",
  "Gen Z",
  "Digital Communication Users",
  "Discount Seekers",
  "Fast Food Consumers",
  "Food Security Advocates"
];

